export const testCsvData = [
    ["TLB4", null, "Incumbent Solution", "text", null,      null, "Avamar", null, "749"],
    ["TLC4", null, "Price",              "text", "$0,0.00", null, "1267.00", null, "749"],
    ["TLD4", null, "Unit",               "text", null,      null, "per TB", null, "749"],
    ["TLE4", null, "Discount %",         "text", null,      null, "80.0%", null, "749"],
    ["TLF4", null, "Adjusted Price",     "text", "$0,0.00", null, "253.40", null, "749"],
    ["TLG4", null, "Maint & Yearly",     "text", null,      null, "18.0%", null, "749"],
    ["TLB5", null, "Incumbent Solution", "text", null,      null, "Commvault", null, "749"],
    ["TLC5", null, "Price",              "text", "0,0.00",  null, "3500.00", null, "749"],
    ["TLD5", null, "Unit",               "text", null,      null, "per FETB", null, "749"],
    ["TLE5", null, "Discount %",         "text", "0,0.0%",  null, "0.80", null, "749"],
    ["TLF5", null, "Adjusted Price",     "text", "0,0.0%",  null, "700.00", null, "749"],
    ["TLG5", null, "Maint & Yearly",     "text", null,      null, "18.0%", null, "749"],
    ["TLB6", null, "Incumbent Solution", "text", null,      null, "DD Boost", null, "749"],
    ["TLC6", null, "Price",              "text", "0,0.00",  null, "1000.00", null, "749"],
    ["TLD6", null, "Unit",               "text", null,      null, "per client", null, "749"],
    ["TLE6", null, "Discount %",         "text", "0,0.0%",  null, "0.80", null, "749"],
    ["TLF6", null, "Adjusted Price",     "text", "0,0.0%",  null, "200.00", null, "749"],
    ["TLG6", null, "Maint & Yearly",     "text", null,      null, "18.0%", null, "749"],
    ["TLB7", null, "Incumbent Solution", "text", null,      null, "Dell/EMC DPS", null, "749"],
    ["TLC7", null, "Price",              "text", "0,0.00",  null, "1100.00", null, "749"],
    ["TLD7", null, "Unit",               "text", null,      null, "per TB", null, "749"],
    ["TLE7", null, "Discount %",         "text", "0,0.0%",  null, "0.80", null, "749"],
    ["TLF7", null, "Adjusted Price",     "text", "0,0.0%",  null, "220.00", null, "749"],
    ["TLG7", null, "Maint & Yearly",     "text", null,      null, "18.0%", null, "749"],
    ["TLB8", null, "Incumbent Solution", "text", null,      null, "IDPA", null, "749"],
    ["TLC8", null, "Price",              "text", "0,0.00",  null, "1535.00", null, "749"],
    ["TLD8", null, "Unit",               "text", null,      null, "per TB", null, "749"],
    ["TLE8", null, "Discount %",         "text", "0,0.0%",  null, "0.70", null, "749"],
    ["TLF8", null, "Adjusted Price",     "text", "0,0.00", null, "460.50", null, "749"],
    ["TLG8", null, "Maint & Yearly",     "text", null, null, "18.0%", null, "749"],
    ["TLB9", null, "Incumbent Solution", "text", null, null, "Networker", null, "749"],
    ["TLC9", null, "Price",              "text", "0,0.00", null, "875.00", null, "749"],
    ["TLD9", null, "Unit",               "text", null, null, "per TB", null, "749"],
    ["TLE9", null, "Discount %",         "text", "0,0.0%", null, "0.70", null, "749"],
    ["TLF9", null, "Adjusted Price",     "text", "0,0.00", null, "262.50", null, "749"],
    ["TLG9", null, "Maint & Yearly",     "text", null, null, "18.0%", null, "749"],
    ["TLB10", null, "Incumbent Solution","text", null, null, "HPE StoreOnce VSA", null, "749"],
    ["TLC10", null, "Price",             "text", "0,0.00", null, "2000.00", null, "749"],
    ["TLD10", null, "Unit",              "text", null, null, "per TB", null, "749"],
    ["TLE10", null, "Discount %",        "text", "0,0.0%", null, "0.80", null, "749"],
]