export const contentData = {
  sections: {
    id: "Section 1",
    order: 1,
    headers: {
      title: {
        type: "element",
        mainTitle: {
          type: "text",
          style: "",
          text: '<h1 style="text-align: left; color: green;">ROI DASHBOARD | 2 Year Projection <span style="float:right;">$0</span></h1>',
        },
        subTitle: {
          type: "text",
          text: `<hr><h3 style="font-size: 22px; font-weight: 700;">Select a section below to review your ROI</h3>`,
        },
        description: `<p style="font-size: 16px;">To calculate your return on investment, begin with the first section below. The information entered therein will automatically populate corresponding fields in the other sections. You will be able to move from section to section to add and/or adjust values to best reflect your organization and process. To return to this screen, click the ROI Dashboard button to the left.</p>`,
      },
    },
    sliders: {
      type: "element",
      classes: "row border-bottom gray-bg dashboard-header",
      elements: [
        {
          type: "card",
          classes: "col-lg-4",
          title: "Improve Win Rate",
          sliderType: "stacked",
          money: 50,
          label: "Conservative Factor:",
          value: 50,
          step: 5,
          id: "CON1940",
        },
        {
          type: "slider",
          classes: "col-lg-4",
          title: "Reduce",
          sliderType: "stacked",
          money: 10,
          label: "Conservative Factor:",
          value: 10,
          step: 5,
          id: "CON1941",
        },
        {
          type: "slider",
          classes: "col-lg-4",
          title: "Additional Selling Time",
          sliderType: "stacked",
          money: 150,
          label: "Conservative Factor:",
          value: 90,
          step: 5,
          id: "CON1942",
        },
        {
          type: "slider",
          classes: "col-lg-4",
          title: "Fast Onboarding",
          sliderType: "stacked",
          money: 22,
          label: "Conservative Factor:",
          value: 70,
          step: 5,
          id: "CON1943",
        },
        {
          type: "slider",
          classes: "col-lg-4",
          title: "Customer Retention",
          sliderType: "stacked",
          money: 11,
          label: "Conservative Factor:",
          value: 30,
          step: 5,
          id: "CON1944",
        },
        {
          type: "slider",
          classes: "col-lg-4",
          title: "Summary",
          sliderType: "stacked",
          money: 750,
          label: "Conservative Factor:",
          value: 20,
          step: 5,
          id: "CON1945",
        },
      ],
    },
  },
};
